# Generated by Django 3.1.7 on 2021-08-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='../../static/images/user.png', upload_to=''),
        ),
    ]
