# Generated by Django 3.1.7 on 2021-08-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210815_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/network/static/images/user.png', upload_to=''),
        ),
    ]
