# Generated by Django 3.1.7 on 2021-08-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20210819_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
    ]
