# Generated by Django 3.1.7 on 2021-08-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_post_isliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isLiked',
        ),
        migrations.AddField(
            model_name='like',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
    ]
