# Generated by Django 3.1.7 on 2021-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20210823_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
